name: Docker CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  backend-docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Backend Docker Image Build
        run: docker build ./backend --file ./backend/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/renting-backend:latest
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Backend Image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/renting-backend:latest

  frontend-docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Frontend Docker Image Build
        run: docker build ./frontend --file ./frontend/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/renting-frontend:latest
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Frontend Image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/renting-frontend:latest
